markdown: kramdown
kramdown:
  toc_levels: 1..3
  auto_ids: true
  parse_block_html: true
  input: GFM
theme: just-the-docs
title: Copilot Chat for Neovim
description: Chat with GitHub Copilot in Neovim
url: https://copilotc-nvim.github.io/CopilotChat.nvim/
