describe('CopilotChat module', function()
  it('should be able to load', function()
    assert.has_no.errors(function()
      require('CopilotChat')
    end)
  end)

  it('should be able to set up', function()
    assert.has_no.errors(function()
      require('CopilotChat').setup({})
    end)
    assert.is_not_nil(require('CopilotChat').chat)
  end)
end)
